#!/usr/bin/env sh

# Clean code
set -o errexit
set -o nounset
set -o noglob

###### Global variables
#
# Controlled configuration source
readonly CONFIG_FILE_PATH="${CONFIG_FILE_PATH:-/etc/default/u-boot}"
readonly CONFIG_DIR_PATH="${CONFIG_DIR_PATH:-/usr/share/u-boot-menu/conf.d}"
readonly PLUGIN_SYS_PATH="${PLUGIN_SYS_PATH:-/usr/share/u-boot-menu/plugins}"
readonly PLUGIN_USER_PATH="${PLUGIN_USER_PATH:-/etc/u-boot-menu/plugins}"
#
## Configuration defaults
U_BOOT_CONFIG_PATH='/boot/extlinux/extlinux.conf'
U_BOOT_TIMEOUT='50'
U_BOOT_PROMPT='1'
U_BOOT_TITLE='U-Boot Menu'
U_BOOT_SEARCH_METHOD='BOOTDIR'
U_BOOT_TARGETS='default rescue'
U_BOOT_TARGET_LABEL='Bootable - Linux${KERNEL_VERSION:+ ${KERNEL_VERSION}}${BOOT_TARGET:+ (${BOOT_TARGET})}'
U_BOOT_TARGET_KERNEL='/boot/vmlinuz${KERNEL_VERSION:+-${KERNEL_VERSION}}'
U_BOOT_TARGET_BOOT_ARGS='root="$(findmnt -nfo SOURCE /)"'
U_BOOT_TARGET_INITRD='/boot/initramfs${KERNEL_VERSION:+-${KERNEL_VERSION}}.img'
U_BOOT_TARGET_FDT=''
U_BOOT_TARGET_FDT_DIR='/boot/dtb/${KERNEL_VERSION}'
#
# Be quiet
readonly LOG_LEVEL="${LOG_LEVEL:-ERROR}"
# loaded plugins
__finder_plugins=""

###### Logging

readonly LOGLEVEL_DEBUG=4
readonly LOGLEVEL_INFO=3
readonly LOGLEVEL_WARN=2
readonly LOGLEVEL_ERROR=1
readonly LOGLEVEL_NONE=0

__current_loglevel=$LOGLEVEL_ERROR

__logprint() {
    >&2 printf "%s: %s\n" "$1" "$2"
}

logging_init() {
    __log_level="$(printf "%s" "${LOG_LEVEL}" | tr '[:lower:]' '[:upper:]')"
    if [ "${__log_level}" = "DEBUG" ]; then
        __current_loglevel=$LOGLEVEL_DEBUG
    elif [ "${__log_level}" = "INFO" ]; then
        __current_loglevel=$LOGLEVEL_INFO
    elif [ "${__log_level}" = "WARN" ]; then
        __current_loglevel=$LOGLEVEL_WARN
    elif [ "${__log_level}" = "ERROR" ]; then
        __current_loglevel=$LOGLEVEL_ERROR
    elif [ "${__log_level}" = "NONE" ]; then
        __current_loglevel=$LOGLEVEL_NONE
    else
        exit 1
    fi
    unset __log_level
}

logd() {
    if [ ${__current_loglevel} -ge $LOGLEVEL_DEBUG ]; then
        __logprint "[DEBUG]" "$1"
    fi
}

logi() {
    if [ ${__current_loglevel} -ge $LOGLEVEL_INFO ]; then
        __logprint "[INFO ]" "$1"
    fi
}

logw() {
    if [ ${__current_loglevel} -ge $LOGLEVEL_WARN ]; then
        __logprint "[WARN ]" "$1"
    fi
}

loge() {
    if [ ${__current_loglevel} -ge $LOGLEVEL_ERROR ]; then
        __logprint "[ERROR]" "$1"
    fi
}

###### Utils

is_function() {
    type "$1" 2>/dev/null | head -n 1 | grep 'function' > /dev/null
}

###### Configuration
#
# Configurations are loaded from two separate places:
#
# 1. ${CONFIG_DIR_PATH}/*.conf : Where distros can place some pre-defined things into
# 2. ${CONFIG_FILE_PATH} : User defined options, will override thoses defined in the above
#

parse_config_file_impl () {
    # shellcheck shell=dash disable=SC1090
    . "${1}" >/dev/null
    # Pick up only useful items
    printf "U_BOOT_CONFIG_PATH='%s'\n" "${U_BOOT_CONFIG_PATH}"
    printf "U_BOOT_TIMEOUT='%s'\n" "${U_BOOT_TIMEOUT}"
    printf "U_BOOT_PROMPT='%s'\n" "${U_BOOT_PROMPT}"
    printf "U_BOOT_TITLE='%s'\n" "${U_BOOT_TITLE}"
    printf "U_BOOT_SEARCH_METHOD='%s'\n" "${U_BOOT_SEARCH_METHOD}"
    printf "U_BOOT_TARGETS='%s'\n" "${U_BOOT_TARGETS}"
    printf "U_BOOT_TARGET_LABEL='%s'\n" "${U_BOOT_TARGET_LABEL}"
    printf "U_BOOT_TARGET_KERNEL='%s'\n" "${U_BOOT_TARGET_KERNEL}"
    printf "U_BOOT_TARGET_BOOT_ARGS='%s'\n" "${U_BOOT_TARGET_BOOT_ARGS}"
    printf "U_BOOT_TARGET_INITRD='%s'\n" "${U_BOOT_TARGET_INITRD}"
    printf "U_BOOT_TARGET_FDT='%s'\n" "${U_BOOT_TARGET_FDT}"
    printf "U_BOOT_TARGET_FDT_DIR='%s'\n" "${U_BOOT_TARGET_FDT_DIR}"

    # Let plugins pick up their configs too
    while IFS= read -r line || [ -n "${line}" ]; do
        [ -z "${line}" ] && continue
        logd "calling parse_config_${line}"
        "parse_config_${line}"
    done << __E_O___F___
$(printf '%s\n' "${__finder_plugins}" | sed -nE 's/^(.+)$/finder_\1/p')
__E_O___F___
}

parse_config_file() {
    eval "$(parse_config_file_impl "$@")"
}

parse_config() {
    while IFS= read -r conf_file; do
        [ -z "${conf_file}" ] && continue
        if [ "${conf_file}" = "${CONFIG_DIR_PATH}/"'*.conf' ]; then
            break
        fi
        logd "Loading system configuration: ${conf_file}"
        parse_config_file "${conf_file}"
    done << __E_O___F___
$(find "${CONFIG_DIR_PATH}" -maxdepth 1 -type f -name '*.conf' 2>/dev/null || true)
__E_O___F___

    if [ -f "${CONFIG_FILE_PATH}" ]; then
        logd "Loading user configuration: ${CONFIG_FILE_PATH}"
        parse_config_file "${CONFIG_FILE_PATH}"
    fi
}

###### Plugins
#

load_finder_plugin () {
    plugin_path="${1}"
    logd "Loading: ${plugin_path}"

    unset get_plugin_id
    # shellcheck shell=dash disable=SC1090
    . "${plugin_path}"

    if ! is_function "get_plugin_id"; then
        loge "Not implemented: get_plugin_id in ${plugin_path}"
        exit 1
    fi
    plugin_id="$(get_plugin_id)"

    if ! is_function "find_kernels_${plugin_id}"; then
        loge "Not implemented: find_kernels_${plugin_id} in ${plugin_path}"
        exit 1
    fi

    if ! is_function "parse_config_finder_${plugin_id}"; then
        loge "Not implemented: parse_config_${plugin_id} in ${plugin_path}"
        exit 1
    fi

    __finder_plugins="$(printf "%s\n%s" "${__finder_plugins}" "${plugin_id}")"
    logd "Finder plugin loaded: ${plugin_id}"

    unset plugin_id
    unset get_plugin_id
    unset plugin_path
}

has_finder_plugin () {
    printf "%s" "${__finder_plugins}" | grep "${1}" >/dev/null
}

filter_sys_plugins_override() {
    sys_plugins="${1}"
    user_plugins_dir="${2}"
    while IFS= read -r line || [ -n "${line}" ]; do
        [ -z "${line}" ] && continue
        plugin_fname="$(basename "${line}")"
        if [ -e "${user_plugins_dir}/${plugin_fname}" ]; then
            logw "User plugin overrides: ${plugin_fname}"
        else
            printf "%s\n" "${line}"
        fi
        unset plugin_fname
        unset line
    done << __E_O___F___
${sys_plugins}
__E_O___F___
    unset sys_plugins
    unset user_plugins_dir
}

load_plugins_impl () {
    plugin_loader="${1}"
    plugin_list="${2}"
    while IFS= read -r line || [ -n "${line}" ]; do
        [ -z "${line}" ] && continue
        "${plugin_loader}" "${line}"
    done << __E_O___F___
${plugin_list}
__E_O___F___
    unset plugin_list
    unset plugin_loader
}

load_plugins () {
    logd "preinstalled plugin dir: ${PLUGIN_SYS_PATH}"
    logd "user plugin dir: ${PLUGIN_USER_PATH}"

    # loading kernel finder plugins
    sys_plugin_finders="$(find "${PLUGIN_SYS_PATH}/finders" -maxdepth 1 -type f -name '*.plugin' 2>/dev/null || true)"
    sys_plugin_finders="$(filter_sys_plugins_override "${sys_plugin_finders}" "${PLUGIN_USER_PATH}/finders")"
    load_plugins_impl "load_finder_plugin" "${sys_plugin_finders}"
    unset sys_plugin_finders

    user_plugin_finders="$(find "${PLUGIN_USER_PATH}/finders" -maxdepth 1 -type f -name '*.plugin' 2>/dev/null || true)"
    load_plugins_impl "load_finder_plugin" "${user_plugin_finders}"
    unset user_plugin_finders
}

find_kernels() {
    if ! has_finder_plugin "${U_BOOT_SEARCH_METHOD}"; then
        loge "finder plugin not implemented: ${U_BOOT_SEARCH_METHOD}"
        exit 1
    fi
    kvers="$("find_kernels_${U_BOOT_SEARCH_METHOD}")"
    echo "${kvers}" | sort -rV
    unset kvers
}

generate_extlinux_head() {
    cat << __E_O___F___
# This file is generated by u-boot-update.
# Any changes will be discarded upon next update.
__E_O___F___
}

generate_extlinux_title() {
    if [ "${U_BOOT_PROMPT}" -eq 0 ] && [ "${U_BOOT_TIMEOUT}" -eq 0 ]; then
        logw "System will always boot into default entry"
    fi
    cat << __E_O___F___
default entry_1
menu title ${U_BOOT_TITLE}
prompt ${U_BOOT_PROMPT}
timeout ${U_BOOT_TIMEOUT}
__E_O___F___
}

generate_extlinux_entry() {
    export KERNEL_VERSION="${1}"
    export BOOT_TARGET="${2}"

    logd "generating for kernel (${KERNEL_VERSION}) target (${BOOT_TARGET})"
#     cat << __E_O___F___
#     menu label $(eval printf "\"%s\"" "\"${U_BOOT_TARGET_LABEL}\"")
#     linux $(eval printf "\"%s\"" "\"${U_BOOT_TARGET_KERNEL}\"")
#     append $(eval printf "\"%s\"" "\"${U_BOOT_TARGET_BOOT_ARGS}\"")
# __E_O___F___
    eval printf "\"\tmenu label %s\n\"" "\"${U_BOOT_TARGET_LABEL}\""
    eval printf "\"\tlinux %s\n\"" "\"${U_BOOT_TARGET_KERNEL}\""
    eval printf "\"\tappend %s\n\"" "\"${U_BOOT_TARGET_BOOT_ARGS}\""
    if [ -n "${U_BOOT_TARGET_INITRD}" ]; then
        eval printf "\"\tinitrd %s\n\"" "\"${U_BOOT_TARGET_INITRD}\""
    fi
    if [ -n "${U_BOOT_TARGET_FDT}" ]; then
        eval printf "\"\tfdt %s\n\"" "\"${U_BOOT_TARGET_FDT}\""
        if [ -n "${U_BOOT_TARGET_FDT_DIR}" ]; then
            logw "Ignoring U_BOOT_TARGET_FDT_DIR"
        fi
    elif [ -n "${U_BOOT_TARGET_FDT_DIR}" ]; then
        eval printf "\"\tfdtdir %s\n\"" "\"${U_BOOT_TARGET_FDT_DIR}\""
    fi
    unset KERNEL_VERSION
    unset BOOT_TARGET
}

# Expected kver format:
# ${KVER}*${KERNEL_FILENAME}
# KVER should be the same as /lib/modules/xxx, while filename should be basename
generate_extlinux() {
    content="$(generate_extlinux_head)"
    content="$(printf "%s\n\n%s" "${content}" "$(generate_extlinux_title)")"

    entry_count=0
    while IFS= read -r line; do
        [ -z "${line}" ] && continue
        entry_count="$(( entry_count + 1 ))"
        logi "Found entry ${entry_count}: ${line}"
        for target in ${U_BOOT_TARGETS}; do
            content="$(printf "%s\n\n%s" "${content}" "label entry_${entry_count}_${target}")"
            content="$(printf "%s\n%s" "${content}" "$(generate_extlinux_entry "${line}" "${target}")")"
        done
    done << __E_O___F___
${1}
__E_O___F___

    if [ $entry_count -eq 0 ]; then
        loge "No kernel entry found"
        exit 1
    fi
    unset entry_count

    mkdir -p "$(dirname "${U_BOOT_CONFIG_PATH}")"
    immefile="$(dirname "${U_BOOT_CONFIG_PATH}")/.$(basename "${U_BOOT_CONFIG_PATH}")"
    logi "Writing to file..."
    logd "setup immediate output: ${immefile}"
    printf "%s\n" "${content}" > "${immefile}"
    logi "Replacing old config..."
    logd "renaming immediate output to: ${U_BOOT_CONFIG_PATH}"
    mv "${immefile}" "${U_BOOT_CONFIG_PATH}"

    logi "Done"
}

main() {
    logging_init
    load_plugins
    parse_config
    generate_extlinux "$(find_kernels)"
}

main "$@"
